apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pytest
  name: pytest
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pytest
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pytest
    spec:
      containers:
      - image: test-python:LOCAL
        imagePullPolicy: Never
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
 
