apiVersion: v1
kind: Service
metadata:
  labels:
    app: pytest
  name: pytest
  namespace: default
spec:
  selector:
    app: pytest
  ports:
  - protocol: "TCP"
    port: 5000
    targetPort: 5000
  type: LoadBalancer