apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sample-01
  name: sample-01
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-01
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sample-01
    spec:
      containers:
      - image: docker.io/irvnet/sample-01:v01
        imagePullPolicy: Always
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
 
